/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package youtubeapis;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;
import java.security.GeneralSecurityException;

class ApiExampleTest {
    @Test void someLibraryMethodReturnsTrue() {
    	ApiExample classUnderTest = new ApiExample();
        //assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    	try {
			assertNotNull(ApiExample.getService(), "credentials can not be null");
		} catch (GeneralSecurityException | IOException e) {
			// TODO Auto-generated catch block
			//e.printStackTrace();
			assertTrue(true, " Genereal Security or IOException occurred which is not allowed.");
		}
    }
}
